### paulirotations.jl
##
# A file for Pauli rotation gates, i.e., gates that are generated by a Pauli string.
# For example PauliRotation(:X, 2)  ->  RX_2(θ) = exp(-i θ/2 X_2) is a Pauli rotation gate.
##
###

# TODO: We should make these type-stable by using tuples and not vectors
"""
    PauliRotation(symbols::Vector{Symbol}, qinds::Vector{Int})

A parametrized Pauli rotation gate acting on the qubits `qinds` with the Pauli string `symbols`.
"""
struct PauliRotation <: ParametrizedGate
    symbols::Vector{Symbol}
    qinds::Vector{Int}
end

"""
    PauliRotation(symbol::Symbol, qind::Int)

Constructor for a `PauliRotation` acting on a single qubit `qind` with the Pauli `symbol`.
"""
function PauliRotation(symbol::Symbol, qind::Int)
    return PauliRotation([symbol], [qind])
end

"""
    PauliRotation(symbols::Union{AbstractArray,Tuple,Base.Generator}, qinds::Union{AbstractArray,Tuple,Base.Generator})

Constructor for a `PauliRotation` acting on the qubits `qinds` with the Pauli string `symbols`. 
Converts the types of the input arguments to the correct types for `PauliRotation`.
"""
function PauliRotation(symbols::Union{AbstractArray,Tuple,Base.Generator}, qinds::Union{AbstractArray,Tuple,Base.Generator})
    return PauliRotation(collect(symbols), collect(qinds))
end

"""
    PauliRotation(symbols, qinds, theta)

Constructor for a frozen `PauliRotation` acting on the qubits `qinds` with the Pauli string `symbols`, and with fixed parameter `theta`.
"""
function PauliRotation(symbols, qinds, theta)
    return FrozenGate(PauliRotation(symbols, qinds), theta)
end

"""
    MaskedPauliRotation(symbols::Vector{Symbol}, qinds::Vector{Int}, term::PauliStringType)

A parametrized Pauli rotation gate acting on the qubits `qinds` with the Pauli string `symbols`.
The `term` is the integer representation of the Pauli string with the correct integer type for the total number of qubits.
This allows for faster application of the gate.
See `tomaskedpaulirotation` for conversion from `PauliRotation`, which is the easiest way to construct a `MaskedPauliRotation`.
"""
struct MaskedPauliRotation{T} <: ParametrizedGate where {T<:PauliStringType}
    symbols::Vector{Symbol}
    qinds::Vector{Int}
    generator_mask::T
end


"""
    PauliRotationUnion

Union type for `PauliRotation` and `MaskedPauliRotation`, useful for functions which handle either agnostically.
"""
PauliRotationUnion = Union{PauliRotation,MaskedPauliRotation}


"""
    _tomaskedpaulirotation(circ::Vector{Gate})

Returns a circuit where `PauliRotation` gates are transformed to `MaskedPauliRotation` gates.
This allows for significantly faster computation with the gate.
"""
function _tomaskedpaulirotation(circ::Vector{G}, nqubits::Integer) where {G<:Gate}
    TT = getinttype(nqubits)
    return _tomaskedpaulirotation(circ, TT)
end

"""
    _tomaskedpaulirotation(circ::Vector{Gate})

Returns a circuit where `PauliRotation` gates are transformed to `MaskedPauliRotation` gates.
This allows for significantly faster computation with the gate.
"""
function _tomaskedpaulirotation(circ::Vector{G}, ::Type{TT}) where {G<:Gate,TT<:PauliStringType}
    masked_circ = copy(circ)
    for (ii, gate) in enumerate(masked_circ)
        if isa(gate, PauliRotation)
            masked_circ[ii] = _tomaskedpaulirotation(gate, TT)
        end
    end
    return masked_circ
end

"""
    _tomaskedpaulirotation(pauli_gate::PauliRotation, nqubits::Integer)

Transforms a `PauliRotation` to a `MaskedPauliRotation` which carries the integer representation of the gate generator.
This allows for significantly faster computation with the gate.
"""
function _tomaskedpaulirotation(pauli_gate::PauliRotation, nqubits::Integer)
    pstr_term = symboltoint(nqubits, pauli_gate.symbols, pauli_gate.qinds)
    return MaskedPauliRotation(pauli_gate.symbols, pauli_gate.qinds, pstr_term)
end

"""
    _tomaskedpaulirotation(frozen_gate::FrozenGate, nqubits::Integer)

Transforms a `FrozenGate` with a `PauliRotation` to a `MaskedPauliRotation` 
which carries the integer representation of the gate generator.
"""
function _tomaskedpaulirotation(frozen_gate::FrozenGate, nqubits::Integer)
    return FrozenGate(_tomaskedpaulirotation(frozen_gate.gate, nqubits), frozen_gate.theta)
end

"""
    _tomaskedpaulirotation(fast_pauli_gate::MaskedPauliRotation, args...)

Return the `MaskedPauliRotation` gate as is.
"""
function _tomaskedpaulirotation(masked_pauli_gate::MaskedPauliRotation, args...)
    return masked_pauli_gate
end

"""
    _tomaskedpaulirotation(pauli_gate::PauliRotation, ::TermType)

Transforms a `PauliRotation` to a `MaskedPauliRotation` which carries the integer representation of the gate generator.
This allows for significantly faster computation with the gate.
"""
function _tomaskedpaulirotation(pauli_gate::PauliRotation, ::Type{TT}) where {TT<:PauliStringType}
    pstr_term = symboltoint(TT, pauli_gate.symbols, pauli_gate.qinds)
    return MaskedPauliRotation(pauli_gate.symbols, pauli_gate.qinds, pstr_term)
end


"""
    commutes(gate::PauliRotation, pstr::PauliString)

Check if a `PauliRotation` commutes with a `PauliString`.
"""
function commutes(gate::PauliRotation, pstr::PauliString)
    return commutes(gate, pstr.term)
end

"""
    commutes(gate::PauliRotationUnion, pstr)

Check if a `PauliRotation` commutes with an integer Pauli string.
"""
function commutes(gate::PauliRotation, pstr::PauliStringType)
    return sum(!commutes(gate_sym, getpauli(pstr, qind)) for (qind, gate_sym) in zip(gate.qinds, gate.symbols)) % 2 == 0
end

"""
    commutes(gate::MaskedPauliRotation, pstr::PauliStringType)

Check if a `MaskedPauliRotation` commutes with an integer Pauli string.
"""
function commutes(gate::MaskedPauliRotation, pstr::PauliStringType)
    return commutes(gate.generator_mask, pstr)
end
